name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Aplicar actualizaciones de seguridad
          # sudo apt update && sudo apt upgrade -y

          cd /var/www/EislekerHaus_Static/
          git fetch origin
          git reset --hard origin/main

          # Install Node.js if npm is not found
          if ! command -v npm &> /dev/null; then
            curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

          # Install dependencies and build the app
          npm install
          npm run build

          # Install pm2 if it is not found
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          # pm2 start npm --name eislekerhaus -- run start
          # Restart the app with pm2 using the production start script
          pm2 restart eislekerhaus --force
          pm2 save --force
